version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/GSA/grace-app
    steps:
      - checkout
      - run:
          name: Lint code
          command: make lint

workflows:
  version: 2

  lint:
    jobs:
      - lint
